<?php

namespace AppBundle\Repository;

/**
 * StudyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
